// Generated by CoffeeScript 1.9.3
(function() {
  $(document).ready(function() {
    var canvas;
    console.log("ready");
    canvas = $("#canvas1");
    return $(window).resize(function() {
      return console.log("resize");
    });
  });

}).call(this);
