// Generated by CoffeeScript 1.9.3
(function() {
  $(document).ready(function() {
    var circle, stage;
    console.log("ready");
    stage = new createjs.Stage("canvas1");
    console.log(stage);
    circle = new createjs.Shape();
    circle.graphics.beginFill("DeepSkyBlue").drawCircle(0, 0, 50);
    circle.x = 100;
    circle.y = 100;
    stage.addChild(circle);
    stage.update();
    $(window).resize(function(e) {
      stage.canvas.width = $(e.target).width();
      stage.canvas.height = $(e.target).height();
      return stage.update();
    });
    return $(window).trigger("resize");
  });

}).call(this);
